# En este archivo de configuración se podrá elegir la base de datos necesaria para jugar.

#Para usar correctamente este archivo de configuración debera introducir la información correctamente, separada en 3 campos:

# - DB_URL: Aqui usted deberá usar la url del JDBC.
# - DB_USER: Aqui usted deberá usar el UserName de la base de datos.
# - DB_PASSWORD: Aqui usted deberá usar la contraseña de la base de datos.

#IMPORTANTE: ¡NO ES NECESARIO EL USO DE COMILLAS!

Config:
  Database:
    DB_URL: jdbc:mysql://localhost/PONCHISAO326
    DB_USER: root
    DB_PASSWORD: 1234